### ISSUE TITLE
filters as an array of structs

### ISSUE THREAD

**Issue by emad-elsaid** [AAbouZaid/golang-playground#1]
in this section : 
https://github.com/AAbouZaid/golang-playground/blob/1fd7136fcd68310aff91102281ba88e6de701cef/flume/flume.go#L21-L25

probably it's better to have it as an array of filters
it could be as follows: 
```go
type Filter struct {
   Source string `toml:"source"`
   Channel string `toml:"channel"`
  Sing string `toml:"sink"`
}

type Filters []Filter
```

or you need the current structure for your output format? as this feels better for me as a data structure.

**Comment by aabouzaid** [comment]
Hmmm, each of `Source, Channel, Sink` should be an array has list of values, they are not string.

ok let met explain what I try to do.

I want to make something like this (like python style)
```
example = {
  'source': {
    'key01': 'val01',
    'key02': 'val02',
    'key03': 'val03',
  },
}

filters = {
  'source': [
    'key01',
    'key02',
  ],
  'channel': [],
  'sink': [],
}

for source_name, source_data in example.items():
  for key,val in source_data.items():
    if key in filters[source_name]:
      print key
```
so this should print key01, key02 only, since that want we want to select/filter.
